export default [
  {
    id: '01',
    menuId: '01',
    type: 'menu',
    title: '基础信息',
    name: '基础信息',
    path: '/projectCenter/info',
    icon: 'iconfont icon-info-circle',
    theme: '#2d1e02',
    children: [],
  },
  {
    id: '02',
    menuId: '01',
    type: 'menu',
    title: '项目文件',
    name: '项目文件',
    path: '/projectCenter/file',
    theme: '#2d1e02',
    icon: 'iconfont icon-folder'
  },
  {
    id: '03',
    menuId: '01',
    type: 'menu',
    title: '组管理',
    name: '组管理',
    path: '/projectCenter/testeeGroup',
    theme: '#2d1e02',
    icon: 'iconfont icon-team',
    children: []
  },
  {
    id: '04',
    menuId: '01',
    type: 'menu',
    title: '机构管理',
    name: '机构管理',
    path: '/projectCenter/organization',
    theme: '#2d1e02',
    icon: 'iconfont icon-cluster',
    children: []
  }, {
    id: '05',
    menuId: '01',
    type: 'menu',
    title: '权限管理',
    name: '权限管理',
    path: '/projectCenter/authorize',
    theme: '#2d1e02',
    icon: 'iconfont icon-Partition',
  }, {
    id: '06',
    menuId: '01',
    type: 'menu',
    title: '用户管理',
    name: '用户管理',
    path: '/projectCenter/user',
    theme: '#2d1e02',
    icon: 'iconfont icon-user',
  },
]
